### ISSUE TITLE
Bug : memory display

### ISSUE THREAD

**Issue by yahwang** [jtpio/jupyterlab-system-monitor#11]
I found a bug(?) while setting config option.

There's difference between using `open_browser` option. Based on the result of psutil, I think the right image would be better.

The result is same even I change a browser(chrome, firefox).

Does this bug(?) apply only to my laptop?

```
Left : jupyter lab (--NotebookApp.open_browser=True) # default option

Right : jupyter lab --NotebookApp.open_browser=False 
```
![screenshot_5](https://user-images.githubusercontent.com/12381530/71643879-93bc5800-2d02-11ea-96cf-9b39c81cd14d.png)

My Laptop:
 - OS : Ubuntu 18.04.3
 - Python: 3.7.5

**Comment by jtpio** [comment]
Thanks @yahwang for the report.

The memory usage indicator gets the value from [nbresuse](https://github.com/yuvipanda/nbresuse), which measures the whole amount of memory used by the notebook server.

It could be that `open_browser` of the notebook server requires more memory indeed: https://github.com/jupyter/notebook/blob/f354740e57f206d67bfb077a9f23bb8d22b6b311/notebook/notebookapp.py#L1865-L1902

**Comment by yahwang** [comment]
Thanks for the reply. I understood the issue.
