### ISSUE TITLE
nodejs is required 

### ISSUE THREAD

**Issue by MauricioFarias** [jtpio/jupyterlab-system-monitor#14]
I executed the installing instructions and this message was shown:

> ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
> 
> Exiting application: jupyter
> 
Is the library required?

**Comment by MauricioFarias** [comment]
Python 3.8.2 64bits

**Comment by jtpio** [comment]
@MauricioFarias yes, Node.js is required to install JupyterLab extensions (see https://jupyterlab.readthedocs.io/en/stable/user/extensions.html#extensions).

You can install it from the website: https://nodejs.org

Or using conda: `conda install -c conda-forge nodejs`
