### ISSUE TITLE
Does this work for jupyter notebook as well?

### ISSUE THREAD

**Issue by sahil0094** [jtpio/jupyterlab-system-monitor#23]
Does this work for jupyter notebook as well?

**Comment by jtpio** [comment]
This extension is only for JupyterLab.

But nbresuse has an extension for the classic notebook that will display the memory usage in the top right corner (no cpu usage yet): https://github.com/yuvipanda/nbresuse#memory-usage-warning-threshold

**Comment by sahil0094** [comment]
Thanks @jtpio

**Comment by jtpio** [comment]
Closing as answered. Don't hesitate to open a new issue if you have any question!
