### ISSUE TITLE
Top bar is blank

### ISSUE THREAD

**Issue by simonwhite71** [jtpio/jupyterlab-system-monitor#28]
I am trying to install this with jupyterlab 2.1.2. It seems to install ok, the top bar works but there is nothing in it.
I am installing like this:
`pip install nbresuse==0.3.4`
`jupyter labextension install       jupyterlab-topbar-extension         jupyterlab-system-monitor`
Any ideas about where I can start to look to debug it?

**Comment by jtpio** [comment]
Thanks @simonwhite71 for reporting.

> pip install nbresuse==0.3.4

Unfortunaly `nbresuse==0.3.4` has a breaking change. Can you try with `nbresuse==0.3.3`?

If it fixes the issue we can add this to the README.

**Comment by simonwhite71** [comment]
Yeah that seems to be working now, thanks for getting back to me so quickly

**Comment by jtpio** [comment]
Thanks @simonwhite71 for checking.

I've added a note to the README to pin nbresuse to 0.3.3 for now.
