### ISSUE TITLE
Going to add GPU verification?

### ISSUE THREAD

**Issue by kwon14** [jtpio/jupyterlab-system-monitor#29]
I praise you for creating this feature.!!

Are you planning to add GPU check function?

It would be perfect if it were added.!!
Thank U :)

**Comment by jtpio** [comment]
Thanks, that would be great indeed!

We would probably need to add support for GPU in nbresuse first: https://github.com/yuvipanda/nbresuse/issues/12

**Comment by jtpio** [comment]
Closing as this would have to be implemented in https://github.com/jupyter-server/jupyter-resource-usage (tracked in https://github.com/jupyter-server/jupyter-resource-usage/issues/12)
