### ISSUE TITLE
License not found

### ISSUE THREAD

**Issue by Boxie5** [jtpio/jupyterlab-system-monitor#33]
There is no info found about the license.

Can we change the codes and use this plugin in our commercial project?

**Comment by jtpio** [comment]
Thanks @Boxie5 for pointing that out.

It was indeed missing and will be fixed in https://github.com/jtpio/jupyterlab-system-monitor/pull/34.

**Comment by jtpio** [comment]
> Can we change the codes and use this plugin in our commercial project?

Yes.

Also don't hesitate to open a PR here (or in [nbresuse](https://github.com/yuvipanda/nbresuse)) if you want to contribute some changes upstream :)

**Comment by Boxie5** [comment]
Great! Thx for your timely response👍
