### ISSUE TITLE
Not showing anything other than memory

### ISSUE THREAD

**Issue by darenr** [jtpio/jupyterlab-system-monitor#37]
![Screen Shot 2020-06-26 at 9 06 38 AM](https://user-images.githubusercontent.com/5496117/85877698-6a015c80-b78c-11ea-955a-da3c1f026389.png)

JupyterLab 2.1.3
nbresuse==0.3.6

**Comment by danielcsj** [comment]
Hi, darenr

Have you created the file ~/.jupyter/jupyter_notebook_config.py? 
Please, run the command below and paste here.

> jupyter labextension list

**Comment by darenr** [comment]
```
JupyterLab v2.1.3
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/csvviewer v2.1.2  enabled  OK
        jupyterlab-system-monitor v0.6.0  enabled  OK
        jupyterlab-topbar-extension v0.5.0  enabled  OK
        jupyterlab_marketplace v2.2.2  enabled  OK
```

**Comment by darenr** [comment]
worked great - thank you

**Comment by dyerdave-cvs** [comment]
This worked for me -- apparently the extension still uses the notebook config file even for lab (which also has its own --generate-config option.  <shrug>.  Thanks for the tip.

**Comment by dyerdave-cvs** [comment]
> r

This worked for me -- apparently the extension still uses the notebook config file even for lab (which also has its own --generate-config option. . Thanks for the tip.

**Comment by dyerdave-cvs** [comment]
> Have you created the file ~/.jupyter/jupyter_notebook_config.py?

Creating this config file worked for me -- apparently the extension still uses the notebook config file even for lab (which also has its own --generate-config option.  Thanks for the tip.
