### ISSUE TITLE
CPU usage > 100%

### ISSUE THREAD

**Issue by jmontoyam** [jtpio/jupyterlab-system-monitor#38]
Hello,

I installed the stable version of jupyterlab-system-monitor, as well as the corresponding dependencies:

jupyter lab --version
2.1.5

jupyterlab-system-monitor v0.6.0  enabled  OK
jupyterlab-topbar-extension v0.5.0  enabled  OK
nbresuse                  0.3.6

I also configured the jupyter_notebook_config.py file in order to track the CPU usage:
c = get_config()

# cpu
c.NotebookApp.ResourceUseDisplay.track_cpu_percent = True
c.NotebookApp.ResourceUseDisplay.cpu_limit = 16

After following these steps I can see the CPU usage, but it shows 100% cpu usage even when I use all the 16 cores (it should report 1600% usage, right?). Is this the expected behavior?...did I miss an extra configuration step?

According to the docs, jupyterlab-system-monitor depends on psutil to show the metrics, but according to the psutil docs, 
the psutil method cpu_percent(interval=None) returns a float representing the process CPU utilization as a percentage which can also be > 100.0 in case of a process running multiple threads on different CPUs. 

Thank you very much for your help! ;)

**Comment by jtpio** [comment]
Thanks @jmontoyam!

Indeed the value is capped to 100% for now, but we should show a greater value as reported by `nbresuse` / `psutil`.

Let me know if you would like to open a PR. We would need to modify this part:

https://github.com/jtpio/jupyterlab-system-monitor/blob/b966c3a345f75a858676356b1fcd762b3ccedc9c/packages/system-monitor-base/src/model.ts#L171-L173

And make sure the values passed to the underlyin `react-sparklines` component are between 0 and 1 here:

https://github.com/jtpio/jupyterlab-system-monitor/blob/b966c3a345f75a858676356b1fcd762b3ccedc9c/packages/system-monitor-base/src/cpuView.tsx#L22-L28

**Comment by jmontoyam** [comment]
Hi @jtpio !

thank you very much for your kind reply. I would love to contribute to this amazing project with a pull request, but I must confess I don't know the typescript language neither the react framework, nevertheless, with your help, I would like to learn the basics so that I can contribute the pull request :). Taking a look to the code, and following your suggestion, I would change these lines
```javascript
      this._currentCpuPercent = this._cpuAvailable
        ? Math.min(1, cpuPercent / 100)
        : 0;
```
by this one

```javascript
      this._currentCpuPercent = this._cpuAvailable ? cpuPercent  : 0;
```
In addition, I would change these lines
```javascript
  const update = (): void => {
    const { currentCpuPercent } = model;
    const newValues = model.values.map((value) => value.cpuPercent);
    const newText = `${(currentCpuPercent * 100).toFixed(0)}%`;
    setText(newText);
    setValues(newValues);
  };
```
by these ones
```javascript
  const update = (): void => {
    const { currentCpuPercent } = model;
    const newValues = model.values.map((value) => value.cpuPercent);
    const newText = `${currentCpuPercent.toFixed(0)}%`;
    setText(newText);
    setValues(newValues);
  };
```
If I understood correctly, we need to make sure the variable ```newValues``` is between 0 and 1, but in order to do so, we need to know the maximum number of logical cpus, is there a way to get this info from typescript?...Googling a little bit I found this function:
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorConcurrentHardware/hardwareConcurrency
Is that the right one?

Thank you very much, and please excuse me for all the naive questions!

**Comment by jtpio** [comment]
Thanks @jmontoyam for taking the time to look into this!

Overall it looks good.

> we need to make sure the variable newValues is between 0 and 1

This is mostly a UI thing so this sparklines doesn't go out of bounds:

![image](https://user-images.githubusercontent.com/591645/86933218-988f1800-c13a-11ea-9ecf-7406cc5a0045.png)

We could try without the clamping between 0 and 1 first and see how it is handled by the react component.

> but in order to do so, we need to know the maximum number of logical cpus, is there a way to get this info from typescript?

Fortunately this step shouldn't be necessary. The UI retrieves the cpu and memory values from the server by doing a request to the server:

https://github.com/jtpio/jupyterlab-system-monitor/blob/b966c3a345f75a858676356b1fcd762b3ccedc9c/packages/system-monitor-base/src/model.ts#L319-L323

And the server is able to provide such information using the `nbresuse` (and underlying `psutil`) packages.

Setting up the development environment might require some work at first, but normally the instructions in the README should help: https://github.com/jtpio/jupyterlab-system-monitor#development
