### ISSUE TITLE
Move to the jupyter-resource-usage repo

### ISSUE THREAD

**Issue by jtpio** [jtpio/jupyterlab-system-monitor#51]
The lab extensions provided in this repo should eventually be moved to https://github.com/jupyter-server/jupyter-resource-usage.

This will avoid having an external dependency on `nbresuse` / `jupyter-resource-usage`.

And using the new distribution system for federated / pre-built extensions in JupyterLab 3.0, it will be easier to have everything installed and working with a single `pip install jupyter-resource-usage`.

There is on-going work to move the status bar item from core lab to `jupyter-resource-usage`: https://github.com/jupyter-server/jupyter-resource-usage/pull/69

Regarding the dependency on the topbar plugin, this could be made optional. With https://github.com/jtpio/jupyterlab-topbar staying as-is and providing the token. For example:

- Check `jupyterlab-topbar` is installed and the `ITopBar` token is available. If so, add the indicators to the topbar just like now.
- If not available, add the indicators to the `top` area instead with `app.shell(widget, 'top')`

This way users will only get the functionality if they ask for it with `pip install jupyterlab-topbar`.

**Comment by dclong** [comment]
The issue https://github.com/jupyter-server/jupyter-resource-usage/pull/69 has been merged. Does it mean that jupyter-resource-usage is preferred over jupyterab-system-monitor now?

**Comment by jtpio** [comment]
> Does it mean that jupyter-resource-usage is preferred over jupyterab-system-monitor now?

Not yet. For now `jupyter-resource-usage` only adds the status bar indicator for JupyterLab.

With this issue the idea would be to move the visual top bar indicator to `jupyter-resource-usage`:

![image](https://user-images.githubusercontent.com/591645/78585243-ce6de900-7839-11ea-94f2-05adcb3555d4.png)

Then when it's done users could do a single `pip install jupyter-resource-usage` to insall everything at once.

**Comment by jtpio** [comment]
Closing as `jupyterlab-system-monitor` has now been integrated in `jupyter-resource-usage`: https://github.com/jupyter-server/jupyter-resource-usage/issues/191
