### ISSUE TITLE
Bad config with `c.NotebookApp.ResourceUseDisplay...`

### ISSUE THREAD

**Issue by JonTong** [jtpio/jupyterlab-system-monitor#55]
On the latest version (`jupyter-resource-usage 0.5.1`, `jupyterlab-topbar 0.6.1` and `jupyterlab-system-monitor 0.8.0`) running on JupyterLab `3.0.9`, I was unable to launch `jupyter lab` with my jupyter lab config file containing the following:
```
c = get_config()
c.NotebookApp.ResourceUseDisplay.mem_limit = 4294967296
c.NotebookApp.ResourceUseDisplay.track_cpu_percent = True
c.NotebookApp.ResourceUseDisplay.cpu_limit = 2
```
Attempting to launch `jupyter lab` would give the error:
`[ ... NotebookApp] Bad config encountered during initialization: Trait, ResourceUseDisplay, not found.`

Without these options in my Jupyter config, I was unable to show memory limits or track/show the CPU usage (as expected).

However, changing this to:
```
c = get_config()
c.ResourceUseDisplay.mem_limit = 4294967296
c.ResourceUseDisplay.track_cpu_percent = True
c.ResourceUseDisplay.cpu_limit = 2
```
worked and displayed memory limits and CPU usage/limits.

Is this expected? Should the `README` be changed if so?

**Comment by jtpio** [comment]
Thanks @JonTong.

It sounds like it's related to this issue: https://github.com/jupyter-server/jupyter-resource-usage/issues/79

It would make sense to also update the docs in this repo for now, before moving the `system-monitor` extension to `jupyter-resource-usage` at some point: https://github.com/jtpio/jupyterlab-system-monitor/issues/51

Would you like to open a PR?

**Comment by JonTong** [comment]
@jtpio Sure, I'll open a PR.
