### ISSUE TITLE
memory and CPU not showing in Jupyter Lab 3.0

### ISSUE THREAD

**Issue by yosit** [jtpio/jupyterlab-system-monitor#56]
The bar does show on the top.
I'm installing this with pip:
```
jupyterlab-topbar
jupyterlab-system-monitor
```
Running this in the docker file:
```
    jupyter labextension install jupyterlab-topbar-extension 
                             jupyterlab-system-monitor 
                             jupyterlab-topbar-text 
                             jupyterlab-theme-toggle

```
Launching it with this:
```
jupyter lab \
  --NotebookApp.ResourceUseDisplay.mem_limit=$(( 16 *1024*1024*1024 )) \
  --NotebookApp.ResourceUseDisplay.track_cpu_percent=True \
  --NotebookApp.ResourceUseDisplay.cpu_limit=$(( 16 )) \
  --NotebookApp.allow_origin='*' \
  --NotebookApp.base_url=/ \
  --NotebookApp.log_format='%(message)s' \
  --NotebookApp.log_level='INFO' \
  --NotebookApp.password='' \
  --NotebookApp.token='' \
  --ip=0.0.0.0 \
  --no-browser \
  "--notebook-dir=$HOME" \
  --port=8888
```

The toolbar shows with the "Hello" and theme switch but not the memory and CPU.

**Comment by jtpio** [comment]
Thanks @yosit for reporting.

Have you tried installing the extension with pip?

```bash
pip install jupyterlab-system-monitor
```

Instead of `jupyter labextension install`.

**Comment by ladychili** [comment]
Same here. I installed jupyterlab-system-monitor with pip.
The top bar not showing metrics, and the terminal keeps returning those error

![image](https://user-images.githubusercontent.com/27876613/109476735-319be600-7ab2-11eb-978f-7d556370e564.png)

**Comment by yosit** [comment]
@jtpio from the instructions I understood I need to do both pip install and jupyterlabextension install

**Comment by iicky** [comment]
I'm also getting the same logs. I have only run `pip install jupyterlab-system-monitor` to install. Here's the versions I am currently running:

```
# pip freeze | grep jupyterlab
jupyterlab==3.0.9
jupyterlab-pygments==0.1.2
jupyterlab-server==2.3.0
jupyterlab-system-monitor==0.8.0
jupyterlab-topbar==0.6.1
```

Any idea where the endpoint `/api/metrics/` went?

**Comment by jtpio** [comment]
> from the instructions I understood I need to do both pip install and jupyter labextension install

@yosit with JupyterLab 3.0 the single `pip install` should be enough,

> Any idea where the endpoint `/api/metrics/` went?

This endpoint is exposed by `jupyter-resource-usage`: https://github.com/jupyter-server/jupyter-resource-usage, which should now be part of the dependencies:

https://github.com/jtpio/jupyterlab-system-monitor/blob/a05a27d4d5be23259a14272f455b621d705b7d89/setup.py#L71

**Comment by yosit** [comment]
@jtpio thanks.
It now shows the memory - only the label without the spike chart.
It's not showing the CPU.

**Comment by jabbera** [comment]
I'm having this same issue. It looks like the metrics api is only returning memory. Any idea why that would be happening?

{"rss": 275681280, "limits": {"memory": {"rss": 0}}}

**Comment by shoegazerstella** [comment]
I am having the same issue on jupyterlab 3.0.

```
jupyterlab @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_1616195786210/work
jupyterlab-drawio==0.8.0
jupyterlab-git==0.30.1
jupyterlab-nvdashboard==0.6.0
jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1601375948261/work
jupyterlab-server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1617134349851/work
jupyterlab-system-monitor==0.8.0
jupyterlab-topbar==0.6.1
jupyterlab-widgets @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_widgets_1609173350931/work
```

Here's what it shows on the top bar:

<img width="330" alt="Schermata 2021-06-01 alle 12 54 01" src="https://user-images.githubusercontent.com/22822597/120312008-7a914f80-c2d8-11eb-946d-b73fa9bbfb88.png">

**Comment by jtpio** [comment]
Linking to https://github.com/jupyter-server/jupyter-resource-usage/issues/91 and https://github.com/jupyter-server/jupyter-resource-usage/issues/86 which sound similar.

**Comment by paravatha** [comment]
@jabbera @jtpio I am using k8s and seeing the issue w.r.t CPU not showing. Memory stats works fine

**Comment by tlvu** [comment]
I also have the same problem.  CPU not showing, only memory is showing.

**Comment by mretkoceri** [comment]
Make sure you restart the jupyterlab after installing the extension.

I also had a similar issue, it appears I mistakenly put letters _gb_ on 
> ~/.jupyter/jupyter_notebook_config.py
`c.ResourceUseDisplay.mem_limit = 256gb *1024*1024*1024`  
as in reality the constant must be an integer.

**Comment by scottwsides** [comment]
I've got the same error. The mem use number shows... but no bars. I'm running jupyterlab=3.3.0 and pip installing jupyterlab-system-monitor. Any progress?

**Comment by EnyMan** [comment]
I had to set the limits for the bars to show.
https://github.com/jtpio/jupyterlab-system-monitor#graphic-display

**Comment by scottwsides** [comment]
I set the limits in the startup for jupyterlab... but still no luck. Mem usage shows but no bars

**Comment by jtpio** [comment]
Closing as `jupyterlab-system-monitor` has now been integrated in `jupyter-resource-usage`: https://github.com/jupyter-server/jupyter-resource-usage/issues/191

Feel free to open a new issue on the `jupyter-resource-usage` repo if needed: https://github.com/jupyter-server/jupyter-resource-usage

Thanks!
