### ISSUE TITLE
Memory consuption shows 0

### ISSUE THREAD

**Issue by ghostshad** [jtpio/jupyterlab-system-monitor#6]
Hello,

I'm running the latest jupyterhub from conda-forge. 

I've installed the system monitor module by running:

jupyter labextension install jupyterlab-topbar-extension jupyterlab-system-monitor

The widget in the top appeared and shows Mem:0.0 B

The endpoint /resuse returns the json and has some meaningfull rss value.

Could you help to investigate the issue?

**Comment by jtpio** [comment]
@ghostshad thanks for the report.

For the endpoint do you mean `/metrics`?

Are there any error in the dev tools console?

**Comment by ghostshad** [comment]
Well, /metrics is working as well.

I've limited the used extensions and don't have any errors now in the console, but the memory is still 0.00

I've checked the same plugin for classical notebooks that uses nsresuse and it works and uses /resuse endpoint for it's data.

Currently I can see the requests for /metrics in the dev console. It has the process_virtual_memory_bytes value there with some float value that looks sane

**Comment by Felihong** [comment]
Hi @jtpio ,

I'm encountering a similar issue here, after installed the extension
```
pip install nbresuse
jupyter labextension install jupyterlab-topbar-extension jupyterlab-system-monitor
```
I saw the memory tab top of the right panel, however this remains `0` the whole time. 

![Screenshot 2020-02-04 at 16 22 17](https://user-images.githubusercontent.com/28823328/73758172-95969280-476a-11ea-8faa-a7c09f97adb4.png)

Any ideas? Thanks.

**Comment by stefanvangastel** [comment]
Same here, running JupyterHub with Kubernetes spawners.

**Comment by jtpio** [comment]
@Felihong @stefanvangastel @ghostshad is the value displayed in the JupyterLab status bar?

![image](https://user-images.githubusercontent.com/591645/78124913-a2ed9780-7410-11ea-9a1b-9b0657252c6f.png)

**Comment by stefanvangastel** [comment]
@jtpio No, no nothing at all next to the kernel icon.

**Comment by jtpio** [comment]
OK that makes sense, since the values in the status bar and in the top bar should be the same.

It looks like there are already a couple of open issues in other repositories, for example this one (and the others it links to): https://github.com/yuvipanda/nbresuse/issues/17

**Comment by stefanvangastel** [comment]
@jtpio Nevermind, somewhere allong the way the `pip install nbresuse` got lost in my dockerefiles... added it and now it works just fine!

**Comment by jtpio** [comment]
great!

**Comment by octavd** [comment]
Hello @stefanvangastel , could you please tell me how did you configure this for KubeSpawner?

Currently i have -> c.KubeSpawner.args = [
  "--ResourceUseDisplay.track_cpu_percent=True",
  "--ResourceUseDisplay.mem_limit=17179869184"
 ]

It's always showing 0... 

@jtpio , i've tried also with:
c = get_config()

c.NotebookApp.ResourceUseDisplay.mem_limit = 17179869184
c.NotebookApp.ResourceUseDisplay.track_cpu_percent = True

and it's the same.

Could you please help?

**Comment by octavd** [comment]
I've solved with the memory - it displays now but the cpu won't display at all
I have a KubeSpawner:

tried with:
c.KubeSpawner.args = [
  "--ResourceUseDisplay.track_cpu_percent=True",
  "--ResourceUseDisplay.cpu_limit=0.75"
] -> nothing

Also with: 
c.NotebookApp.ResourceUseDisplay.track_cpu_percent = True
c.NotebookApp.ResourceUseDisplay.cpu_limit = 0.75

or 
c.KubeSpawner.ResourceUseDisplay.track_cpu_percent = True
c.KubeSpawner.ResourceUseDisplay.cpu_limit = 0.75

and still nothing.

If i open the /metrics it shows -> {"rss": 66908160, "limits": {"memory": {"rss": 536870912, "warn": false}, "cpu": {"cpu": 0.75, "warn": false}}, "cpu_percent": 0.0, "cpu_count": 8}

Any ideas?

**Comment by jtpio** [comment]
@octavd which version of `jupyterlab-system-monitor` are you using? The latest that includes the CPU indicator is `0.6.0`.

**Comment by octavd** [comment]
oh, so that's why it wasn't working. :)
thank you very much, jtpio!

**Comment by jtpio** [comment]
Closing as answered.

Don't hesitate to open a new issue to discuss more.
