### ISSUE TITLE
CpuViewComponent disabled because request to metric too early

### ISSUE THREAD

**Issue by jhgoebbert** [jtpio/jupyterlab-system-monitor#64]
`api/metrics/v1` might not be ready when the following line checks for `model.cpuAvailable`
https://github.com/jtpio/jupyterlab-system-monitor/blob/main/packages/system-monitor-base/src/cpuView.tsx#L39

I can see this behaviour at our setup. As a workaround a reload of the whole jlab-webpage fixes it.

**Comment by jtpio** [comment]
Closing as `jupyterlab-system-monitor` has now been integrated in `jupyter-resource-usage`: https://github.com/jupyter-server/jupyter-resource-usage/issues/191

Feel free to open a new issue on the `jupyter-resource-usage` repo if needed: https://github.com/jupyter-server/jupyter-resource-usage

Thanks!
