### ISSUE TITLE
How can I change the memory displaying unit?

### ISSUE THREAD

**Issue by sjoh-kw** [jtpio/jupyterlab-system-monitor#69]
In Readme.md, the example shows the unit of memory usage in GB, but my browser shows in MB.
How can I change this unit?

**Comment by jtpio** [comment]
Thanks @sjoh-kw.

The unit should automatically be adjusted based on the current usage. See the source for the relevant logic: 

https://github.com/jtpio/jupyterlab-system-monitor/blob/926069c8faaf62b74a02bf5fb0692729d3643467/packages/system-monitor-base/src/model.ts#L256-L284

**Comment by jtpio** [comment]
Closing as `jupyterlab-system-monitor` has now been integrated in `jupyter-resource-usage`: https://github.com/jupyter-server/jupyter-resource-usage/issues/191

Feel free to open a new issue on the `jupyter-resource-usage` repo if needed: https://github.com/jupyter-server/jupyter-resource-usage

Thanks!
