### ISSUE TITLE
Memory limit not displayed

### ISSUE THREAD

**Issue by kwon14** [jtpio/jupyterlab-system-monitor#72]
Hello
Thanks for providing nice features of jupyterlab-system-monitor.
I'm using Jupyter with Docker on k8s.
Execute it with the following command.

Jupyterlab version: 3.1.7 (latest version)
installation:
pip install jupyterlab-system-monitor
execution:
jupyter lab --NotebookApp.ResourceUseDisplay.mem_limit=4294967296

memory is displayed, but memory limit is not displayed.

Please check if it is a problem with Jupyter 3.x or how to solve it.
thank you.

**Comment by jtpio** [comment]
Closing as `jupyterlab-system-monitor` has now been integrated in `jupyter-resource-usage`: https://github.com/jupyter-server/jupyter-resource-usage/issues/191

Feel free to open a new issue on the `jupyter-resource-usage` repo if needed: https://github.com/jupyter-server/jupyter-resource-usage

Thanks!
