### ISSUE TITLE
Is there any way to add disk usage monitoring metrics?

### ISSUE THREAD

**Issue by mlussati** [jtpio/jupyterlab-system-monitor#78]
I intend to add the disk usage metric I can quickly add what are the points I need to pay attention to.

**Comment by jtpio** [comment]
Closing as `jupyterlab-system-monitor` has now been integrated in `jupyter-resource-usage`: https://github.com/jupyter-server/jupyter-resource-usage/issues/191

Let's continue the discussion in https://github.com/jupyter-server/jupyter-resource-usage/issues/186.

Thanks!
