### ISSUE TITLE
Cut new release for multi cpu support?

### ISSUE THREAD

**Issue by dleen** [jtpio/jupyterlab-system-monitor#83]
Hi Jeremy (@jtpio),

Thanks for the really awesome extension! I was wondering if you have the time to cut a new release which includes #80 as I think this is a useful feature to have?

On an unrelated note: I can respond to a bunch of the issues here since I was doing some Docker investigation myself. I can't resolve them but just letting you know 😄

**Comment by albertmichaelj** [comment]
I would just like to echo this. I am preparing teaching infrastructure for this coming academic year, and it would be really great to have the fix for multi-cpu support so that my students can see how their code is utilizing multiple cores.

**Comment by jtpio** [comment]
Closing as `jupyterlab-system-monitor` has now been integrated in `jupyter-resource-usage`: https://github.com/jupyter-server/jupyter-resource-usage/issues/191

We can continue the discussion in https://github.com/jupyter-server/jupyter-resource-usage/issues/16 which looks related.

Thanks!
