### ISSUE TITLE
Monitor tool not showing up for JupyterLab 1.2.21

### ISSUE THREAD

**Issue by sag31Bamane** [jtpio/jupyterlab-system-monitor#88]
I tried installing jupyterlab-system-monitor older version to get it working on jupyterLab 1.2.21 however its not showing up. 
May I know what are the package dependencies and there respective version required for this extension to work for jupyterLab 1.2.21.
Note : I am trying this extension in Sagemaker jupyterlab.

**Comment by sag31Bamane** [comment]
<img width="881" alt="Screen Shot 2022-03-21 at 3 38 52 PM" src="https://user-images.githubusercontent.com/5796355/159374702-3189357f-b202-4616-9f0b-e75b8fc926a4.png">

**Comment by sag31Bamane** [comment]
<img width="898" alt="Screen Shot 2022-03-21 at 3 40 33 PM" src="https://user-images.githubusercontent.com/5796355/159374800-e3e5f48b-a2de-4b5b-8c39-8ce0744156cb.png">

**Comment by jtpio** [comment]
Closing as `jupyterlab-system-monitor` has now been integrated in `jupyter-resource-usage`: https://github.com/jupyter-server/jupyter-resource-usage/issues/191

Feel free to open a new issue on the `jupyter-resource-usage` repo if needed: https://github.com/jupyter-server/jupyter-resource-usage

Thanks!
