### ISSUE TITLE
Update README for POSIX config?

### ISSUE THREAD

**Issue by therealnlee** [jtpio/jupyterlab-system-monitor#91]
I'm using Jupyterlab on jupyterhub now,
and tried to show CPU usage (which I believe the default value is `False`)
and the config below (as in current README) did not work properly for jupyterlab

```
# POSIX shell
jupyter lab --NotebookApp.ResourceUseDisplay.mem_limit=$(( size_in_GB *1024*1024*1024)) \
            --NotebookApp.ResourceUseDisplay.track_cpu_percent=True \
            --NotebookApp.ResourceUseDisplay.cpu_limit=$(( number_of_cpus ))
```

After I changed `NotebookApp` to `ServerApp` for these configs, I got what I wanted.
I would be much better to update README for the users like me. Thanks!

**Comment by jtpio** [comment]
Closing as `jupyterlab-system-monitor` has now been integrated in `jupyter-resource-usage`: https://github.com/jupyter-server/jupyter-resource-usage/issues/191

Feel free to open a new issue on the `jupyter-resource-usage` repo to improve the `README.md`: https://github.com/jupyter-server/jupyter-resource-usage

Thanks!
