### ISSUE TITLE
Failed to show CPU usage in the pip installation

### ISSUE THREAD

**Issue by euigfdbguiwerin93** [jtpio/jupyterlab-system-monitor#95]
Hi! Thank you for this really useful plugin! I tried to follow the README and install the plugin via pip but failed to see the CPU usage even if I configured as guided.

However, then I followed the process of https://github.com/jtpio/jupyterlab-system-monitor#development and successfully make CPU usage chart shown. Also, I need to run development process under the home directory of this repo.

I wonder if the plugin is not well packaged or the artifacts are not well linked?

**Comment by maxima120** [comment]
same problem here. latest ubuntu. latest python3 and **jupyter lab**.
there was no jupyter notebook config file so i created it by `jupyter notebook --generate-config` and set it up as suggested here. 

```
c.ResourceUseDisplay.mem_limit = 30000000000
c.ResourceUseDisplay.track_cpu_percent = True
c.ResourceUseDisplay.cpu_limit = 20
```

I now have memory usage figure but not the graph and no CPU usage. 

![image](https://user-images.githubusercontent.com/10121753/189487158-885eaf76-8632-42cc-8856-056b034a2f55.png)

I tried to use command line with the same effect

```
jupyter lab --NotebookApp.ResourceUseDisplay.mem_limit=$(( 30000000000 ))             
                  --NotebookApp.ResourceUseDisplay.track_cpu_percent=True
                  --NotebookApp.ResourceUseDisplay.cpu_limit=$(( 20 ))

```

**Comment by chenge191** [comment]
same proble ,did anyone has the solution

**Comment by jtpio** [comment]
Closing as `jupyterlab-system-monitor` has now been integrated in `jupyter-resource-usage`: https://github.com/jupyter-server/jupyter-resource-usage/issues/191

Feel free to open a new issue on the `jupyter-resource-usage` repo if needed: https://github.com/jupyter-server/jupyter-resource-usage

Thanks!
