### ISSUE TITLE
How much resource it occupies?

### ISSUE THREAD

**Issue by kangsan0420** [jtpio/jupyterlab-system-monitor#96]
I'm considering this repo to the jupyter env. for our DS team.
I'd like to know that how much resource (for server and client each) it occupies.
Is there any chance that this package slows down our jupyter dev env?

**Comment by jtpio** [comment]
Closing as `jupyterlab-system-monitor` has now been integrated in `jupyter-resource-usage`: https://github.com/jupyter-server/jupyter-resource-usage/issues/191

Feel free to open a new issue on the `jupyter-resource-usage` repo if needed: https://github.com/jupyter-server/jupyter-resource-usage

Thanks!
